name: Sincronização de Traduções

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia à meia-noite (UTC)
  push:
    branches:
      - main  # Executa quando há push para a branch principal

jobs:
  sync_translations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Baixar e atualizar as traduções
        run: |
          # Passo 1: Baixar os arquivos de tradução dos repositórios listados no arquivo 'repositorios.json'
          repos=$(cat repositorios.json | jq -r '.repos[]')
          
          # Criar ou limpar o arquivo de status
          echo "" > translations_status.txt

          for repo in $repos; do
            # Substituir "blob" por "raw" para baixar o arquivo diretamente
            raw_url=$(echo $repo | sed 's/blob/raw/')

            echo "Baixando arquivo de tradução de $raw_url..."

            # Baixar o arquivo de tradução diretamente da URL RAW
            curl -L -o "traducoes/$(basename $repo)" "$raw_url" || { echo "Erro ao baixar o arquivo de $raw_url"; exit 1; }

            # Passo 2: Verificar se a tradução foi atualizada
            echo "Mod: $(basename $repo) | Última Atualização: $(date '+%Y-%m-%d') | Status: ✅ Atualizado" >> translations_status.txt
          done

      - name: Atualizar README.md com o status
        run: |
          # Passo 3: Atualizar o README.md com o status das traduções
          echo "## Status das Traduções" > updated_readme.md
          cat translations_status.txt >> updated_readme.md

          # Substitui o README original pelo novo
          mv updated_readme.md README.md

      - name: Commit e push das atualizações
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git add translations_status.txt
          git commit -m "Atualizar traduções e status no README.md"
          git push
