name: Sincronizar Traduções

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  sync-translations:
    runs-on: ubuntu-latest

    steps:
    # Configurar repositório
    - name: Checar o repositório
      uses: actions/checkout@v3

    # Instalar Node.js e dependências (se necessário)
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Executar o script de sincronização
    - name: Baixar e atualizar traduções
      run: |
        mkdir -p translations
        curl -L -o translations/en_us.json https://raw.githubusercontent.com/satisfyu/Vinery/1.20.1/common/src/main/resources/assets/vinery/lang/en_us.json
        echo "Traduções sincronizadas com sucesso!" > translations_status.txt

    # Atualizar o README.md com o status
    - name: Atualizar README.md com o status das traduções
      run: |
        echo "## Status das Traduções" > README.md
        echo "" >> README.md
        echo "As traduções foram atualizadas com sucesso no último workflow." >> README.md
        cat translations_status.txt >> README.md

    # Commit e push das mudanças
    - name: Commit e push das alterações
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Atualizar traduções e status no README.md"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Ezequiel9898/Tradu-o.git
        git push origin main
