name: Atualizar Traduções de Mods

on:
  push:
    branches:
      - main  # Ajuste conforme sua branch principal

jobs:
  update-mods:
    runs-on: ubuntu-latest  # O ambiente de execução (Ubuntu)

    steps:
      # 1. Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Configurar o Python 3.x
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 3. Instalar dependências (como requests)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Executar o script de atualização
      - name: Run Update Script
        run: |
          python3 scripts/check_updates.py

      # 5. Comitar e enviar as mudanças, caso haja alguma atualização
      - name: Commit changes if necessary
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Atualizando traduções e status dos mods"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
