# File: .github/workflows/update_mods.yml
name: Update Mods

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: python -m pip install --upgrade pip requests

      - name: Executar script de atualização
        run: python scripts/check_updates.py

      - name: Verificar mudanças no repositório
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "Sem mudanças para commitar."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Mudanças detectadas."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commitar e enviar mudanças
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Atualização automática de mods"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
