name: Update Mods Status

on:
  schedule:
    - cron: '0 0 * * *'  # Executar diariamente a meia-noite
  push:
    branches:
      - main

jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Update Script
        run: python3 scripts/check_updates.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Atualizar status dos mods"
          git push
