name: Update Mods Status

on:
  push:
    branches:
      - main

jobs:
  update-mods:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run update script
      run: |
        python3 scripts/check_updates.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Atualizando o status dos mods"
        git push
